### PR TITLE
add support for scoped package names

### PR DESCRIPTION
**Pull request by voronianski**
Allow to multi post such names as `@cycle/core` or `@risingstack/graffiti`

### CODE REVIEW

**Comment by voronianski** [comment]
@maxogden it will be useful to have this in new version ASAP. Thanks!

**Comment by voronianski** [comment]
@maxogden my second commit is related to this issue - https://github.com/jfhbrook/wzrd.in/issues/116

**Comment by voronianski** [comment]
Leaving this thread here as related as well - https://github.com/voronianski/esnextbin/issues/4

**Comment by maxogden** [comment]
@voronianski I added you as a collaborator, feel free to merge and publish, I wont be able to get to this for a little bit

**Comment by voronianski** [comment]
@maxogden thanks

**Pull request merged**
